### PR TITLE
Remove allure-junit5 dependency and bump gradle to 8.1.1

### PR DESCRIPTION
**Pull request by paulgus**
Testing of the snapshot version showed that the allure-junit5 dependency is redundant. I have also bumped the gradle version

### CODE REVIEW

**Comment by glockbender** [comment]
@Kantis hi. Could you check it please?

**Comment by glockbender** [comment]
@Kantis @sksamuel ping guys. We are really need this fix to finish our integration with allure

**Comment by Denis-26** [comment]
@Kantis @sksamuel Hi! When will this changes be released?

**Comment by Cat61** [comment]
> @Kantis @sksamuel Hi! When will this changes be released?

+1

**Comment by OlegKDev** [comment]
@Kantis @sksamuel Hello! I appreciate the efforts you put into this project. Do you think there are prospects for implementing these changes? Thank you

**Comment by Kantis** [comment]
Sorry for the delay. Has anyone tried out the snapshot? I can publish a new version tonight

**Pull request merged**
